(SIMP-10414) Fix sssd-sudo service permissions
simp/pupmod-simp-sssd pull request #110
Opened 2021-08-05 13:53 UTC by trevor-vaughan

- Add an override for sssd-sudo.service to start it as root:root. This aligns
  with how sssd itself would start the service and the daemon cannot access
  /var/lib/sss/db/config.ldb otherwise.

SIMP-10414 #close

2021-08-09 13:55 UTC, lnemsick-simp requested changes
On EL7 and EL8 hosts,seeing message `/bin/chown: cannot access '/var/log/sssd/sssd_sudo.log': No such file or directory` every time I `sudo`

2021-08-09 16:08 UTC, lnemsick-simp commented
https://gitlab.com/simp/pupmod-simp-sssd/-/jobs/1480429727, https://gitlab.com/simp/pupmod-simp-sssd/-/jobs/1480677481,  and https://gitlab.com/simp/pupmod-simp-sssd/-/jobs/1480429729 all show a selinux context change, which caused the tests to fail.  Doesn't happen on other similar jobs.  Do we have a race condition that could be managed?

2021-08-17 12:45 UTC, trevor-vaughan commented
@lnemsick-simp Told the dropin file to ignore the selinux defaults

2021-08-17 13:39 UTC, trevor-vaughan commented
@lnemsick-simp Added an ExecStartPre to make sure that the log file gets created properly

2021-08-18 12:36 UTC, lnemsick-simp approved these changes

2021-08-18 12:38 UTC, merged